apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: "OpenAPI and MongoDB proof of concepts"
deploy:
  helm:
    releases:
      - name: mongodb
        remoteChart: bitnami/mongodb
        setValues:
          auth.username: eshva
          auth.password: changeit
          auth.database: admin
          auth.rootUser: admin
          auth.rootPassword: admin
portForward:
  - resourceType: Service
    resourceName: mongodb
    port: 27017
    localPort: 40001
