apiVersion: skaffold/v2beta21
kind: Config
metadata:
  name: "OpenAPI and MongoDB proof of concepts"
build:
  artifacts:
    - image: business-user-bff
      context: .
      docker:
        dockerfile: service.dockerfile
deploy:
  kubectl:
    manifests:
      - service.resources.yaml
  helm:
    releases:
      - name: mongodb
        remoteChart: bitnami/mongodb
        setValues:
          auth.username: eshva
          auth.password: changeit
          auth.database: admin
          auth.rootUser: admin
          auth.rootPassword: admin
portForward:
  - resourceType: Service
    resourceName: mongodb
    port: 27017
    localPort: 40001
  - resourceType: Service
    resourceName: business-user-bff
    port: 443
    localPort: 40101
