apiVersion: v1
kind: Service
metadata:
  name: business-user-bff
spec:
  selector:
    app: business-user-bff
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-user-bff
  labels:
    app: business-user-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-user-bff
  template:
    metadata:
      labels:
        app: business-user-bff
    spec:
      containers:
        - name: business-user-bff
          image: business-user-bff
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          env:
            - name: SERVICE_DocumentStorage__ConnectionString
              value: "mongodb://mongodb:27017"
            - name: SERVICE_DocumentStorage__DatabaseName
              value: "business-user-bff"
            - name: SERVICE_DocumentStorage__UserName
              value: "eshva"
            - name: SERVICE_DocumentStorage__Password
              value: "changeit"
            - name: SERVICE_DocumentCollections__ProductLimitRevisionPages
              value: "ProductLimitRevisionPages"
